### ISSUE TITLE
cannot find module 'react-xml-viewer'

### ISSUE THREAD

**Issue by JanakiKandukuri** [alissonmbr/react-xml-viewer#1]
Could not find a declaration file for module 'react-xml-viewer'. 'c:/Users/admin.janaki.kanduku/Desktop/git_code/UI.Activities.Janaki_Kandukuri/Remediation/node_modules/react-xml-viewer/dist/index.js' implicitly has an 'any' type.
  Try `npm install @types/react-xml-viewer` if it exists or add a new declaration (.d.ts) file containing `declare module 'react-xml-viewer';

**Comment by alissonmbr** [comment]
Please give me more information about the issue. Which version of React, node, npm? Are you using typescript?

**Comment by fdemello** [comment]
Ran into the same issue and had to add `declare module 'react-xml-viewer'` to `react-app-env.d.ts`.
