### ISSUE TITLE
overflowBreak={true} doesn't seem to be working

### ISSUE THREAD

**Issue by MadalenaPavao** [alissonmbr/react-xml-viewer#44]
I have tried to add the props overflowBreak={true} in the Sandbox project, but it doesn't seem to work:
![image](https://user-images.githubusercontent.com/32294501/173545082-f52425cf-51ee-4c66-903e-61ed78c6d31f.png)

**Comment by Han1s** [comment]
This is because overflowBreak is a theme property. Add `overflowBreak: true` to the customTheme object to make it work.
