### ISSUE TITLE
React 18 not support

### ISSUE THREAD

**Issue by christiantigre** [alissonmbr/react-xml-viewer#50]
Hello, I am Try install react-xml-viewer

node: 18.13
react: 18.2.0

npm ERR! Found: react@18.2.0
npm ERR! node_modules/react
npm ERR!   react@"^18.2.0" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer react@">= 16.8.4 < 18.0.0" from react-xml-viewer@1.3.0      
npm ERR! node_modules/react-xml-viewer
npm ERR!   react-xml-viewer@"*" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.

**Comment by BoKKeR** [comment]
Seconded

**Comment by alissonmbr** [comment]
I'm rewriting the code, to work with react 18 and to get rid of the stream-browserify with webpack5 and improve things

**Comment by damianhorne-esgglobal** [comment]
@alissonmbr any update on this?

**Comment by alissonmbr** [comment]
@damianhorne-esgglobal probably I'll release version 2.0.0 this week.

**Comment by alissonmbr** [comment]
Version 2.0.0-beta.4 published. Version 2.0.0 comming soon

**Comment by damianhorne-esgglobal** [comment]
Appears to be working great for me now. Nice job!

**Comment by alissonmbr** [comment]
Version 2.0.0 released with compatibility with react 18
