### ISSUE TITLE
return new line if defined whidt

### ISSUE THREAD

**Issue by draro** [alissonmbr/react-xml-viewer#6]
Is there a way to break a line if this is exceeding the containing div?
for exaple, i have a div of 1000px and within the div i use the XMLViewer. Is there a way to keep a relation with the div size?

**Comment by alissonmbr** [comment]
The version 1.1.0 you can pass as theme the variable overflowBreak: true.
For example:
```
import React, { Component } from 'react'
import XMLViewer from 'react-xml-viewer'

const xml = '<hello attr="World" />'
const customTheme = {
  overflowBreak: true
}

export default class App extends Component {
  render () {
    return (
      <div>
        <XMLViewer xml={xml} theme={customTheme} />
      </div>
    )
  }
}
```
