### ISSUE TITLE
Error when buiild image

### ISSUE THREAD

**Issue by felixgotama** [alissonmbr/react-xml-viewer#79]
![image](https://github.com/user-attachments/assets/9716b3a8-cd32-4dbf-b445-cd90dea90f6c)
I have a problem. Can you help me?

Failed to compile.
./node_modules/react-xml-viewer/dist/index.es.js 2274:16
Module parse failed: Unexpected token (2274:16)
File was processed with these loaders:
 * ./node_modules/babel-loader/lib/index.js
You may need an additional loader to handle the result of these loaders.
| function Zl(e, t) {
|   var r = typeof e;
>   return t = t ?? zl, !!t && (r == "number" || r != "symbol" && Jl.test(e)) && e > -1 && e % 1 == 0 && e < t;
| }
| var Ql = Zl,
Error: error building at STEP "RUN npm run build": error while running runtime: exit status 1

**Comment by vaamartyni** [comment]
> ![image](https://private-user-images.githubusercontent.com/20558171/355029884-9716b3a8-cd32-4dbf-b445-cd90dea90f6c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY0NDI0OTQsIm5iZiI6MTcyNjQ0MjE5NCwicGF0aCI6Ii8yMDU1ODE3MS8zNTUwMjk4ODQtOTcxNmIzYTgtY2QzMi00ZGJmLWI0NDUtY2Q5MGRlYTkwZjZjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTE1VDIzMTYzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBjNGVlNGI5MDQ2MWZmMDgwYWE0ODM0ZjE5MTdhZTZkMjJkNzEzNjdjZGE4ZGU3MDM0MDAyYTRhZjEzMGZlZWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.evt3mvQ5Xobu51ChpQlxU4nK4pqmDh1qQr2Wmu9BU5s) I have a problem. Can you help me?
> 
> Failed to compile. ./node_modules/react-xml-viewer/dist/index.es.js 2274:16 Module parse failed: Unexpected token (2274:16) File was processed with these loaders:
> 
> * ./node_modules/babel-loader/lib/index.js
>   You may need an additional loader to handle the result of these loaders.
>   | function Zl(e, t) {
>   |   var r = typeof e;
> 
> > return t = t ?? zl, !!t && (r == "number" || r != "symbol" && Jl.test(e)) && e > -1 && e % 1 == 0 && e < t;
> > | }
> > | var Ql = Zl,
> > Error: error building at STEP "RUN npm run build": error while running runtime: exit status 1

Hey! I just solved this issue.

Turns out react-xml-viewer uses modern JavaScript features like the nullish coalescing operator (??) and optional chaining (?.), which older browsers don't support without transpilation.

To fix it, you need to add these Babel plugins:

**@babel/plugin-transform-nullish-coalescing-operator
@babel/plugin-transform-optional-chaining**

If you're still having trouble, just share your Webpack and Babel configs, and we'll figure it out together!
