### ISSUE TITLE
Missing types declaration in package.json

### ISSUE THREAD

**Issue by davemssavage** [alissonmbr/react-xml-viewer#80]
Importing XMLViewer in a typescript file causes the warning

`Could not find a declaration file for module 'react-xml-viewer'`

The fix is simple as types file already exists in source so add: 

`"types": "dist/index.d.ts" `

to package.json

**Comment by alissonmbr** [comment]
Thanks you @davemssavage for reporting the issue. It's fixed on version 2.0.2
